const $=id=>document.getElementById(id);
const bilingual=(cz,en)=>$('mode').value==='easy'?cz+' / '+en:cz;
const levels=['Vyberte tvar a pád','Vyberte tvar nebo předložku','Doplňte odpověď','Přeložte celou větu','Opravte chybu'];
const levelsEn=['Choose form and case','Choose form or preposition','Write the missing phrase','Translate the whole sentence','Correct the mistake'];
const cases=[['1','nominativ','kdo? co?'],['2','genitiv','koho? čeho?'],['3','dativ','komu? čemu?'],['4','akuzativ','koho? co?'],['6','lokál','o kom? o čem?'],['7','instrumentál','kým? čím?']];
let queue=exercises.slice(),index=0,attempted=new Set(),correct=new Set(),checked=false;
try{const s=JSON.parse(localStorage.getItem('czechGovernmentV1')||'null');if(s){$('mode').value=s.mode||'easy';attempted=new Set(s.attempted||[]);correct=new Set(s.correct||[]);}}catch{}
function save(){try{localStorage.setItem('czechGovernmentV1',JSON.stringify({mode:$('mode').value,attempted:[...attempted],correct:[...correct]}));}catch{}}
function mix(a){return a.map(v=>({v,r:Math.random()})).sort((a,b)=>a.r-b.r).map(x=>x.v)}
function hintText(e){return $('mode').value==='easy'?e.hintCz+' / '+e.hintEn:e.hintCz}
function activeSet(){return exercises.filter(e=>$('setFilter').value==='all'||e.set===$('setFilter').value)}
function fillVerbs(){const verbs=[...new Set(activeSet().map(e=>e.verb))].sort((a,b)=>a.localeCompare(b,'cs'));$('verbFilter').innerHTML='<option value="all">'+bilingual('Všechna slovesa v sadě','All verbs in this set')+'</option>'+verbs.map(v=>`<option value="${v}">${v} (${activeSet().filter(e=>e.verb===v).length})</option>`).join('')}
function filterQueue(){queue=activeSet().filter(e=>$('verbFilter').value==='all'||e.verb===$('verbFilter').value);index=0;render()}
function textLabels(){const labels={title:['České pády a předložky','Czech cases & prepositions'],subtitle:['150 sloves • 375 situací • vazby, pády a shoda','150 verbs • 375 situations • government, cases & agreement'],modeLabel:['Režim','Mode'],levelLabel:['Úroveň','Level'],setLabel:['Sada','Set'],verbLabel:['Sloveso','Verb'],formLabel:['Správný výraz','Correct phrase'],caseLabel:['Pád doplněného výrazu','Case of the missing phrase'],check:['Zkontrolovat','Check'],next:['Další','Next'],speak:['Poslechnout','Speak'],hintButton:['Nápověda','Hint'],shuffle:['Zamíchat','Shuffle'],skip:['Přeskočit','Skip'],record:['🎙 Namluvit odpověď','Dictate answer'],rulesTitle:['Přehled vazeb a pádů','Patterns and cases']};for(const [id,t]of Object.entries(labels))$(id).textContent=bilingual(...t);$('level').innerHTML=levels.map((x,i)=>`<option value="${i+1}">${i+1}. ${bilingual(x,levelsEn[i])}</option>`).join('');$('setFilter').innerHTML='<option value="all">'+bilingual('Všech 150 sloves · všechny konstrukce','All 150 verbs · all constructions')+'</option><option value="homework">'+bilingual('Domácí úkol · původních 38','Homework · original 38')+'</option><option value="expanded">'+bilingual('Základní sada · dalších 112','Core expansion · 112')+'</option><option value="variation">'+bilingual('Nové vazby · 46','New government patterns · 46')+'</option><option value="agreement">'+bilingual('Shoda v minulém čase · 179','Past-tense agreement · 179')+'</option>';fillVerbs();$('case').innerHTML='<option value="">'+bilingual('Vyberte pád','Choose case')+'</option>'+cases.map(c=>`<option value="${c[0]}">${c[0]}. ${c[1]} · ${c[2]}</option>`).join('');$('rules').innerHTML='<p>'+bilingual('Učte se celou vazbu: sloveso + předložka + pád. Pád vybíráte pro výraz v mezeře.','Learn the whole pattern: verb + preposition + case. Select the case of the missing phrase.')+'</p><table><thead><tr><th>'+bilingual('Sloveso','Verb')+'</th><th>'+bilingual('Vazba a vysvětlení','Pattern and explanation')+'</th></tr></thead><tbody>'+exercises.map(e=>`<tr><td>${e.verb}</td><td>${hintText(e)}</td></tr>`).join('')+'</tbody></table>';$('footer').textContent=bilingual('150 sloves, 375 procvičovacích situací a 1 875 úloh v pěti úrovních. Původní sada z domácího úkolu: 38 sloves. Výsledky se ukládají v tomto prohlížeči. Hlasový vstup přepisuje řeč; nehodnotí výslovnost. Překlad se kontroluje podle vzorové věty, ne podle všech možných formulací.','150 verbs, 375 practice situations and 1,875 tasks across five levels. Original homework set: 38 verbs. Results are saved in this browser. Voice input transcribes speech; it does not assess pronunciation. Translation checking uses the model sentence, not every possible wording.');}
function levelTwo(e){if(e.agreement&&e.verbOptions){return {prompt:e.full.replace(e.agreement.form,'___'),answer:e.agreement.form,options:mix(e.verbOptions)}}const match=e.answer.match(/^(na|o|s|se|z|ze|do|od|za|pro|v|ve|k|ke|po|před) (.+)$/);if(match&&e.id%2===0)return {prompt:e.prompt.replace('___','___ '+match[2]),answer:match[1],options:mix([match[1],...['na','o','s','z','do','od','za','pro'].filter(x=>x!==match[1]).slice(0,2)])};return {prompt:e.prompt,answer:e.answer,options:e.options}}
function render(){const e=queue[index],l=+$('level').value;checked=false;$('position').textContent=`${index+1} / ${queue.length}`;$('bar').style.width=((index+1)/queue.length*100)+'%';$('levelName').textContent=bilingual(levels[l-1],levelsEn[l-1]);$('verb').textContent=e.verb;$('instruction').textContent=bilingual(['Vyberte výraz i jeho pád.','Vyberte správný výraz.','Doplňte celý výraz do mezery.','Přeložte větu do češtiny.','Napište celou větu správně.'][l-1],['Choose the phrase and its case.','Choose the correct phrase.','Write the entire missing phrase.','Translate the sentence into Czech.','Rewrite the whole sentence correctly.'][l-1]);$('sentence').textContent=l===4?e.en:l===5?e.wrong:l===2?levelTwo(e).prompt:e.prompt;$('translation').textContent=$('mode').value==='easy'&&l!==4?e.en:'';$('dropdowns').classList.toggle('hidden',l>2);$('caseBox').classList.toggle('hidden',l!==1);$('writing').classList.toggle('hidden',l<3);$('form').innerHTML='<option value="">'+bilingual('Vyberte výraz','Choose phrase')+'</option>'+mix(l===2?levelTwo(e).options:e.options).map(v=>`<option>${v}</option>`).join('');$('case').value='';$('answer').value='';$('voiceStatus').textContent='';$('feedback').className='feedback hidden';$('hint').className='hint hidden';$('check').classList.remove('hidden');$('next').classList.add('hidden');$('score').textContent=bilingual('Správně na první pokus','Correct first try')+`: ${correct.size} / ${attempted.size}`;}
function normalise(s){return s.normalize('NFC').toLocaleLowerCase('cs').replace(/[.,!?;:„“"']/g,'').replace(/\s+/g,' ').trim()}
function check(){const e=queue[index],l=+$('level').value;const val=l<3?$('form').value:$('answer').value;if(!val.trim()||(l===1&&!$('case').value)){show(bilingual('Nejdřív vyplňte odpověď.','Enter an answer first.'),false);return}const key=e.id+'-'+l,expected=l===2?levelTwo(e).answer:l<4?e.answer:e.full;let ok=normalise(val)===normalise(expected)&&(l!==1||$('case').value===e.case);if(!attempted.has(key)&&ok)correct.add(key);attempted.add(key);save();show(ok?bilingual('Správně!','Correct!')+' '+hintText(e):bilingual('Zkuste to znovu. Vzorová odpověď:','Try again. Model answer:')+' '+expected+(l===1?' · '+e.case+'. pád':'')+' — '+hintText(e),ok);if(ok){checked=true;$('check').classList.add('hidden');$('next').classList.remove('hidden')}$('score').textContent=bilingual('Správně na první pokus','Correct first try')+`: ${correct.size} / ${attempted.size}`;}
function show(text,ok){$('feedback').className='feedback '+(ok?'good':'bad');$('feedback').textContent=text}
function advance(){index=(index+1)%queue.length;render()}
$('check').onclick=check;$('next').onclick=advance;$('skip').onclick=advance;$('shuffle').onclick=()=>{queue=mix(queue);index=0;render()};$('hintButton').onclick=()=>{$('hint').textContent=hintText(queue[index]);$('hint').classList.toggle('hidden')};$('level').onchange=render;$('verbFilter').onchange=filterQueue;$('setFilter').onchange=()=>{fillVerbs();filterQueue()};$('mode').onchange=()=>{const l=$('level').value,v=$('verbFilter').value,set=$('setFilter').value;textLabels();$('setFilter').value=set;fillVerbs();$('level').value=l;$('verbFilter').value=v;save();render()};
$('speak').onclick=()=>{if(!('speechSynthesis'in window)){show(bilingual('Prohlížeč nepodporuje čtení nahlas.','This browser does not support speech playback.'),false);return}speechSynthesis.cancel();const e=queue[index],l=+$('level').value;const u=new SpeechSynthesisUtterance(l===4&&!checked?e.en:e.full);u.lang=l===4&&!checked?'en-GB':'cs-CZ';const voice=speechSynthesis.getVoices().find(v=>v.lang.startsWith(u.lang.slice(0,2)));if(voice)u.voice=voice;u.rate=.85;speechSynthesis.speak(u)};
for(const ch of 'áčďéěíňóřšťúůýž'){let b=document.createElement('button');b.textContent=ch;b.type='button';b.onclick=()=>{const a=$('answer'),start=a.selectionStart,end=a.selectionEnd;a.setRangeText(ch,start,end,'end');a.focus()};$('chars').append(b)}
const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;let listening=false,recognition;
$('record').onclick=()=>{if(!Recognition){$('voiceStatus').textContent=bilingual('Hlasový vstup zde není dostupný. Zkuste Chrome nebo Edge, nebo odpověď napište.','Voice input is unavailable here. Try Chrome or Edge, or type your answer.');return}if(listening){recognition.stop();return}recognition=new Recognition();recognition.lang='cs-CZ';recognition.interimResults=false;recognition.onstart=()=>{listening=true;$('voiceStatus').textContent=bilingual('Poslouchám…','Listening…')};recognition.onresult=event=>{$('answer').value=event.results[0][0].transcript;$('voiceStatus').textContent=bilingual('Zkontrolujte přepis a opravte ho před odesláním.','Review and edit the transcript before checking.')};recognition.onerror=event=>{$('voiceStatus').textContent=bilingual('Hlasový vstup se nepodařil: ','Voice input failed: ')+event.error};recognition.onend=()=>{listening=false};try{recognition.start()}catch{$('voiceStatus').textContent=bilingual('Mikrofon se nepodařilo spustit.','Could not start the microphone.')}};
$('answer').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();checked?advance():check()}};textLabels();render();
